name: wallet_utils
description: A dart ravencoin transaction signing library.
version: 3.1.4
homepage: https://github.com/moontreeapp/wallet_utils

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bech32: ^0.2.2
  bip32: ^2.0.0
  bip39: ^1.0.6
  bs58check: ^1.0.2
  bs58: ^1.0.2
  collection: ^1.19.1
  hex: ^0.2.0
  meta: ^1.16.0
  pointycastle: ^3.9.1
  convert: ^3.1.2
  tuple: ^2.0.2

dev_dependencies:
  test: ^1.17.5
